djangoblog/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
]

djangoblog/articles/urls.py
from django.conf.urls import url
from . import views

app_name = 'articles'

# url pattern read in order!
urlpatterns = [
    url(r'^$', views.article_list, name="list"),
    url(r'^create/$', views.article_create, name="create"),
    url(r'^(?P<id>[\d*]+)/$', views.article_detail, name="detail"),
]

djangoblog/djangoblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls, name="admin"),
    url(r'^articles/', include('articles.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^about/$', views.about, name="about"),
    url(r'^index/$', views.home, name="index"),
    #url(r'^$', views.home, name="home"),
    url(r'^$', include('articles.urls'), name="home"),
]

urlpatterns += staticfiles_urlpatterns()

djangoblog/accounts/models.py
from django.db import models

# Create your models here.

djangoblog/articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here. Database
# python manage.py makemigrations
# python manage.py migrate

max_snippet_length = 50

class Article(models.Model): # DB Table name
  title = models.CharField(max_length=101)
  body = models.TextField()
  date = models.DateTimeField(auto_now_add=True) # automatically without user input
  author = models.ForeignKey(User, default=None)

  def __str__(self): # makes getting self print its own title instead
    return self.title

  def snippet(self): # show only first XX letters of body
    if len(self.body) <= max_snippet_length:
      return self.body
    else:
      return self.body[:50] + '...'
    

djangoblog/articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body']

djangoblog/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from django.contrib.auth import login, logout

# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST) 

        # validation of form
        if form.is_valid():
            user = form.save()
            #login the user
            login(request, user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #login the user
            user = form.get_user()
            login(request, user)

        if 'next' in request.POST:
            return redirect(request.POST.get('next'))
        else:
            return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form}) 


def logout_view(request):
    if request.method == 'POST':
        logout(request)
    return redirect('articles:list')

djangoblog/articles/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Article
from django.contrib.auth.decorators import login_required
from . import forms
# Create your views here.

def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles/article_list.html', {'articles' : articles})

def article_detail(request, id):
    article = Article.objects.get(id=id)
    return render(request, 'articles/article_detail.html', {'article' : article})

@login_required(login_url= "/accounts/login/")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.author = request.user
            myform.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', {'form' : form})

djangoblog/djangoblog/views.py
"""

function which is called when user access url

"""

from django.http import HttpResponse
from django.shortcuts import render

def home(request):
  # return HttpResponse("This is an Home Page response")
    return render(request, 'home.html')

def about(request):
  # return HttpResponse("This is an about response")
    return render(request, 'about.html')

djangoblog/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}

<form class="loginform" action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    {{form}}
    {% if request.GET.next %}
        <input type="hidden" name="next" value="{{ request.GET.next }}">
    {% endif %}
    <input type="submit" value= "Login">

</form>
{% endblock %}

djangoblog/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}

<form class="signupform" action="/accounts/signup/" method="post">
    {% csrf_token %}
    <input type="submit" value= "Signup">
    {{form}}
    <br>
    <input type="submit" value= "Signup">

</form>
{% endblock %}

djangoblog/articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Articles</h1>
    <hr>
    <div class="article-create">
        <form class="form" action="{% url 'articles:create' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create">
        </form>
    </div>
{% endblock %}

djangoblog/articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<link rel="stylesheet" href="/static/article.css">

<div class="article-detail">
    <div class="article">
        <div class="articletitle">
            {{ article.title }}
        </div>
        <div class="articlebody" >
            {{ article.body }}
        </div>
        <div class="articledate" >
           {{ article.author }}
           <br> 
           {{ article.date }}
        </div>
    </div>
</div>
{% endblock %}

djangoblog/articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Articles</h1>
    <hr>
    <div class="articles">
        {% for article in articles %}
        <div class="article">
            <h2><a href="{% url 'articles:detail' id=article.id %}"> {{ article.title}} </a></h2>
            
            <p> {{ article.snippet}} </p>
            <p> {{ article.date}} </p>
            <hr>
        </div>
        {% endfor %}
    </div>
{% endblock %}

djangoblog/templates/about.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>About</title>
    </head>
    <body>
        <h1>This is About page</h1>
        <p>
            Admin User
            <br>
            User: admin
            <br>
            Pass: admin123
        </p>
        <a href="{% url 'home' %}">Homepage</a>
    </body>
</html>

djangoblog/templates/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<link rel="stylesheet" href="/static/homestyle.css">
<html>
    <head>
        <meta charset="utf-8">
        <title>Articles</title>
        <link ref="stylesheet" href="{% static 'homestyle.css' %}">
    </head>
    <body>
        <div class="wrapper">
            <h1><a href="{% url 'articles:list' %}">Django Blog</a></h1>
            {% if user.is_authenticated %}
            <form class="logout-link" action="{% url 'accounts:logout' %}" method="POST">
                {% csrf_token %}
                <button type="submit" >Logout</button>
            </form>
             {% endif %}
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'articles:create' %}">New Article</a></li>
                    {% else %}
                        <li><a href="{% url 'accounts:login' %}">Login</a></li>
                        <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                    {% endif %}
                    
                </ul>
            </nav>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

djangoblog/templates/home.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <title>Homepage</title>
    </head>
    <body>
        <p>Welcome to Homepage</p>
        <a href="{% url 'admin:index' %}">Admin Login</a>
        <hr>
        <a href="{% url 'accounts:login' %}">User Login</a>
        <hr>
        <a href="{% url 'articles:list' %}">Articles Main</a>
        <hr>
        <a href="{% url 'about' %}">About</a>
    </body>
</html>